"""Fix hired_at default value

Revision ID: 31ae0aa8e38d
Revises: 0b205b2baf7f
Create Date: 2026-02-26 21:26:28.652295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31ae0aa8e38d"
down_revision: Union[str, Sequence[str], None] = "0b205b2baf7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
