"""Add role to employees and fix relationships

Revision ID: 0b205b2baf7f
Revises: 95d12ca48ed3
Create Date: 2026-02-21 15:49:25.562654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b205b2baf7f"
down_revision: Union[str, Sequence[str], None] = "95d12ca48ed3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    employeerole_enum = sa.Enum(
        'ADMIN', 'HR', 'LOGISTICS', 'PRODUCTION', 'QA', 'EMPLOYEE',
        name='employeerole',
        create_type=True
    )
    employeerole_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "departments",
        "description",
        existing_type=sa.VARCHAR(length=300),
        nullable=True,
    )
    op.add_column(
        "employees",
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "HR",
                "LOGISTICS",
                "PRODUCTION",
                "QA",
                "EMPLOYEE",
                name="employeerole",
            ),
            nullable=False,
            server_default='EMPLOYEE'
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "role")
    op.alter_column(
        "departments",
        "description",
        existing_type=sa.VARCHAR(length=300),
        nullable=False,
    )

    sa.Enum(name='employeerole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
